site_name: MicroKeras
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: material/library
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy  # Add this line to enable code copy buttons

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - microkeras

nav:
  - Home: index.md
  - API Reference:
    - Activations: api/activations.md
    - Datasets: api/datasets.md
    - Layers: api/layers.md
    - Losses: api/losses.md
    - Models: api/models.md
    - Operations: api/operations.md
    - Optimizers: api/optimizers.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/microkeras
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/microkeras/

copyright: Copyright &copy; 2023 Your Name
